export enum EVENTS {

  CONNECTED = 'CONNECTED',

  CREATE_ROOM = 'CREATE_ROOM',

  JOIN_ROOM = 'JOIN_ROOM',

  ROOM_CREATED = 'ROOM_CREATED',

  ROOM_JOINED = 'ROOM_JOINED',
  
  ERROR = 'ERROR',

  MOVE = 'MOVE',

  CHESS_STATE = 'CHESS_STATE',

  CHESS_FEN = 'CHESS_FEN',

  CHESS_HISTORY = 'CHESS_HISTORY',

  PLAYER_LEFT = 'PLAYER_LEFT',

  TIME_CONTROL_SETUP = 'TIME_CONTROL_SETUP',

  SYNC_CLOCK = 'SYNC_CLOCK',

  FALL_OF_FLAG = 'FALL_OF_FLAG',

  AUTO_RESIGNED = 'AUTO_RESIGNED'
}